;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Item.med.A",DevComment="")
+GameplayTagList=(Tag="Item.med.B",DevComment="")
+GameplayTagList=(Tag="Item.med.C",DevComment="")
+GameplayTagList=(Tag="Item.med.H",DevComment="")
+GameplayTagList=(Tag="Item.med.I",DevComment="")
+GameplayTagList=(Tag="Item.med.M",DevComment="")
+GameplayTagList=(Tag="Item.med.O",DevComment="")
+GameplayTagList=(Tag="Item.med.P",DevComment="")
+GameplayTagList=(Tag="Item.med.R",DevComment="")

